Algoritmo "semnome"
//Fazer um algoritmo que pergunte a idade de uma pessoa, e ao final, informe na tela se a pessoa é menor de
//idade, se é maior de idade, ou se é maior de 65 anos.
Var
idade: inteiro


Inicio
Escreva("Digite a sua idade: ")
leia(idade)

se idade < 18 entao
   escreva("Você é menor de idade")
senao
   se idade <= 65 entao
      escreva("Você é maior de idade")
   senao:
         escreva("Você é maior de 65 anos")
fimse
fimse
Fimalgoritmo


Fimalgoritmo