Algoritmo "exemplo2"
//Pergunte um numero ao usuario e informe se o numero se ele é par ou impar
Var
// Seção de Declarações das variáveis 
num1: inteiro
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe um numero:")
leia(num1)

num <- (num1%2)

se (num = 0)entao
   escreva("O seu numero é par")
senao
     escreva("O seu numero é impar")
fimse



Fimalgoritmo