Algoritmo "exemplo enquanto"
//Exibir todos os numeros existentes na sequencia de 1 a 500
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exebindo os Numeros de 1 até 500:")
contador <- 1
enquanto (contador <= 500)faca
         escreval(contador)
         contador <- (contador + 1)
fimenquanto

Fimalgoritmo