Algoritmo "semnome"
//Fazer um algoritmo que leia o numerador e o denominador de uma fração, e informe como resposta o
//número decimal correspondente a esta fração.
Var
// Seção de Declarações das variáveis 
nume, numer : inteiro
resul : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira o numerador:")
leia(nume)

escreval("Insira o denominador:")
leia(numer)

resul <- nume / numer


escreval("O resultado da Fração é", resul)
Fimalgoritmo