Algoritmo "exercicio09"
//
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Insira um numero de 1 a 7:")
leia(num)
escolha num
caso 1
escreval("Segunda-Feira")
caso 2
escreval("Terça-Feira")
caso 3
escreval("Quarta-Feira")
caso 4
escreval("Quinta-feira")
caso 5
escreval("Sexta-Feira)
caso 6
escreval("Sabado")
caso 7
escreval("Domingo")
fimescolha
Fimalgoritmo